server:
  port: ${proxyPort}

## -DproxyPort=8080 -DproxyContext=/api/hello -DbackendService=http://localhost:8088/api/hello

spring:
  cloud:
    gateway:
      routes:
      - id: hello_route
        uri: ${backendService}
        predicates:
        - Path=${proxyContext}

logging:
  level:
    io.github.kimmking: ERROR
    org: ERROR
